use B2BSolution
go

CREATE TABLE DBO.TB_CONTRATO
(
	ID_CONTRATO			INT PRIMARY KEY IDENTITY,
	ID_CLIENTE			INT,
	ID_EQUIPAMENTO		INT,
	VL_TARIFA_LOCAL		DECIMAL(18,2) NOT NULL,
	VL_TARIFA_LDN		DECIMAL(18,2) NOT NULL,
	VL_TARIFA_VC1		DECIMAL(18,2) NOT NULL,
	VL_TARIFA_VC2		DECIMAL(18,2) NOT NULL,
	VL_TARIFA_VC3		DECIMAL(18,2) NOT NULL,
	VL_CONSUMO_MINIMO	DECIMAL(18,2),
	DS_CADENCIA_FIXA	VARCHAR(6),
	DS_CADENCIA_MOVEL	VARCHAR(6),
	DT_CONTRATO			DATETIME,
	DIA_VENCIMENTO		INT,
	VL_INSTALACAO		DECIMAL(18,2),
	ID_PRAZO_CONTRATUAL	INT,
	ID_VENDEDOR			INT
)
GO


ALTER TABLE TB_CONTRATO
ADD CONSTRAINT FK_CONTRATO_EQUIPAMENTO FOREIGN KEY (ID_EQUIPAMENTO) 
    REFERENCES TB_EQUIPAMENTOS (ID_EQUIPAMENTO) 

ALTER TABLE TB_CONTRATO
ADD CONSTRAINT FK_PRAZO_CONTRATUAL FOREIGN KEY (ID_PRAZO_CONTRATUAL) 
    REFERENCES TB_PRAZO_CONTRATUAL (ID_PRAZO_CONTRATUAL) 
    
ALTER TABLE TB_CONTRATO
ADD CONSTRAINT FK_CONTRATO_CLIENTE FOREIGN KEY (ID_CLIENTE) 
    REFERENCES TB_CLIENTE (ID_CLIENTE) 

ALTER TABLE TB_CONTRATO
ADD CONSTRAINT FK_CONTRATO_VENDEDOR FOREIGN KEY (ID_VENDEDOR) 
    REFERENCES TB_VENDEDORES (ID_VENDEDOR) 