use B2BSolution
go

CREATE TABLE DBO.TB_CLIENTE
(
	ID_CLIENTE		INT PRIMARY KEY IDENTITY,
	DOCUMENTO		VARCHAR(14),
	NOME			VARCHAR(500),
	TP_PESSOA		VARCHAR(2),
	ID_ENDERECO		INT,
	ID_CONTATO		INT,
	FL_ATIVO		BIT
)
GO

ALTER TABLE TB_CLIENTE
ADD CONSTRAINT FK_CLIENTE_ENDERECO FOREIGN KEY (ID_ENDERECO) 
    REFERENCES TB_ENDERECO (ID_ENDERECO) 

ALTER TABLE TB_CLIENTE
ADD CONSTRAINT FK_CLIENTE_CONTATO FOREIGN KEY (ID_CONTATO) 
    REFERENCES TB_CONTATO (ID_CONTATO) 
    
ALTER TABLE TB_CLIENTE
ADD CONSTRAINT UK_DOCUMENTO_CLIENTE UNIQUE (DOCUMENTO)