use B2BSolution
go

CREATE TABLE DBO.TB_ENDERECO
(
	ID_ENDERECO		INT PRIMARY KEY IDENTITY,
	RUA				VARCHAR(200),
	NUMERO			VARCHAR(6),
	COMPLEMENTO		VARCHAR(50),
	CEP				VARCHAR(8),
	BAIRRO			VARCHAR(100),
	CIDADE			VARCHAR(50),
	ESTADO			VARCHAR(2)
)
GO