USE B2BSolution
GO

CREATE TABLE DBO.TB_PAGAMENTO
(
	ID_PAGAMENTO		INT PRIMARY KEY IDENTITY,
	DT_PAGAMENTO		DATETIME,
	VL_GASTO			DECIMAL(18,2),
	VL_PAGO				DECIMAL(18,2),
	ID_CONTRATO			INT,
	FL_PAGO				BIT
)
GO

ALTER TABLE TB_PAGAMENTO
ADD CONSTRAINT FK_PAGAMENTO_CONTRATO FOREIGN KEY (ID_CONTRATO)
	REFERENCES TB_CONTRATO (ID_CONTRATO)