use B2BSolution
go

CREATE TABLE DBO.TB_VENDEDORES
(
	ID_VENDEDOR		INT PRIMARY KEY IDENTITY,
	ID_CONTATO		INT,
	NOME			VARCHAR(500),
	DOCUMENTO		VARCHAR(14),
	COMISSAO		DECIMAL(2,1),
	TP_VENDEDOR		INT,
	FL_ATIVO		BIT
)
GO

ALTER TABLE TB_VENDEDORES
ADD CONSTRAINT FK_VENDEDORES_ENDERECO FOREIGN KEY (ID_ENDERECO) 
    REFERENCES TB_ENDERECO (ID_ENDERECO) 
    
ALTER TABLE TB_VENDEDORES
ADD CONSTRAINT FK_VENDEDORES_CONTATO FOREIGN KEY (ID_CONTATO) 
    REFERENCES TB_CONTATO (ID_CONTATO) 
    
ALTER TABLE TB_VENDEDORES
ADD CONSTRAINT FK_VENDEDORES_TIPO FOREIGN KEY (TP_VENDEDOR) 
    REFERENCES TB_TIPO_VENDEDORES (ID_TIPO_VENDEDOR) 
    
ALTER TABLE TB_VENDEDORES
ADD CONSTRAINT UK_DOCUMENTO_VENDEDORES UNIQUE (DOCUMENTO)