//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2BSolution.Financeiro.Formulario.EquipamentosService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EquipamentosService.IInserirOf_Equipamentos")]
    public interface IInserirOf_Equipamentos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInserirOf_Equipamentos/Incluir", ReplyAction="http://tempuri.org/IInserirOf_Equipamentos/IncluirResponse")]
        int Incluir(B2BSolution.Financeiro.Entidades.Equipamentos entidades);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInserirOf_Equipamentos/Incluir", ReplyAction="http://tempuri.org/IInserirOf_Equipamentos/IncluirResponse")]
        System.Threading.Tasks.Task<int> IncluirAsync(B2BSolution.Financeiro.Entidades.Equipamentos entidades);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInserirOf_EquipamentosChannel : B2BSolution.Financeiro.Formulario.EquipamentosService.IInserirOf_Equipamentos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InserirOf_EquipamentosClient : System.ServiceModel.ClientBase<B2BSolution.Financeiro.Formulario.EquipamentosService.IInserirOf_Equipamentos>, B2BSolution.Financeiro.Formulario.EquipamentosService.IInserirOf_Equipamentos {
        
        public InserirOf_EquipamentosClient() {
        }
        
        public InserirOf_EquipamentosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InserirOf_EquipamentosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InserirOf_EquipamentosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InserirOf_EquipamentosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Incluir(B2BSolution.Financeiro.Entidades.Equipamentos entidades) {
            return base.Channel.Incluir(entidades);
        }
        
        public System.Threading.Tasks.Task<int> IncluirAsync(B2BSolution.Financeiro.Entidades.Equipamentos entidades) {
            return base.Channel.IncluirAsync(entidades);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EquipamentosService.IListarTodosOf_Equipamentos")]
    public interface IListarTodosOf_Equipamentos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListarTodosOf_Equipamentos/ListarTodos", ReplyAction="http://tempuri.org/IListarTodosOf_Equipamentos/ListarTodosResponse")]
        B2BSolution.Financeiro.Entidades.Equipamentos[] ListarTodos(B2BSolution.Financeiro.Entidades.Equipamentos entidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListarTodosOf_Equipamentos/ListarTodos", ReplyAction="http://tempuri.org/IListarTodosOf_Equipamentos/ListarTodosResponse")]
        System.Threading.Tasks.Task<B2BSolution.Financeiro.Entidades.Equipamentos[]> ListarTodosAsync(B2BSolution.Financeiro.Entidades.Equipamentos entidade);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IListarTodosOf_EquipamentosChannel : B2BSolution.Financeiro.Formulario.EquipamentosService.IListarTodosOf_Equipamentos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListarTodosOf_EquipamentosClient : System.ServiceModel.ClientBase<B2BSolution.Financeiro.Formulario.EquipamentosService.IListarTodosOf_Equipamentos>, B2BSolution.Financeiro.Formulario.EquipamentosService.IListarTodosOf_Equipamentos {
        
        public ListarTodosOf_EquipamentosClient() {
        }
        
        public ListarTodosOf_EquipamentosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ListarTodosOf_EquipamentosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListarTodosOf_EquipamentosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListarTodosOf_EquipamentosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public B2BSolution.Financeiro.Entidades.Equipamentos[] ListarTodos(B2BSolution.Financeiro.Entidades.Equipamentos entidade) {
            return base.Channel.ListarTodos(entidade);
        }
        
        public System.Threading.Tasks.Task<B2BSolution.Financeiro.Entidades.Equipamentos[]> ListarTodosAsync(B2BSolution.Financeiro.Entidades.Equipamentos entidade) {
            return base.Channel.ListarTodosAsync(entidade);
        }
    }
}
