CREATE DATABASE B2BSolution
go

use B2BSolution
go

--CREATE TABLE DBO.TB_ENDERECO
--(
--	ID_ENDERECO		INT PRIMARY KEY IDENTITY,
--	RUA				VARCHAR(200),
--	NUMERO			VARCHAR(6),
--	COMPLEMENTO		VARCHAR(50),
--	CEP				VARCHAR(8),
--	BAIRRO			VARCHAR(100),
--	CIDADE			VARCHAR(50),
--	ESTADO			VARCHAR(2)
--)
--GO

--CREATE TABLE DBO.TB_CONTATO
--(
--	ID_CONTATO		INT PRIMARY KEY IDENTITY,
--	NOME			VARCHAR(100),
--	EMAIL			VARCHAR(200),
--	TELEFONE		VARCHAR(8),
--	CELULAR			VARCHAR(9),
--)
--GO

--CREATE TABLE DBO.TB_VENDEDORES
--(
--	ID_VENDEDOR		INT PRIMARY KEY IDENTITY,
--	ID_CONTATO		INT,
--	NOME			VARCHAR(500),
--	DOCUMENTO		VARCHAR(14),
--	COMISSAO		DECIMAL(2,1),
--	TP_VENDEDOR		INT,
--	FL_ATIVO		BIT
--)
--GO

--CREATE TABLE DBO.TB_TIPO_VENDEDORES
--(
--	ID_TIPO_VENDEDOR INT PRIMARY KEY IDENTITY,
--	DS_VENDEDOR		 VARCHAR(100)
--)
--GO

--DROP TABLE TB_EQUIPES
--CREATE TABLE DBO.TB_EQUIPES
--(
--	ID_EQUIPE		INT PRIMARY KEY IDENTITY,
--	ID_VENDEDOR		INT,
--	ID_CANAL		INT
--)
--GO

--CREATE TABLE DBO.TB_EQUIPAMENTOS
--(
--	ID_EQUIPAMENTO	INT PRIMARY KEY IDENTITY,
--	MARCA			VARCHAR(200),
--	MODELO			VARCHAR(200),
--	NUMERO_SERIE    VARCHAR(200)
--)
--GO

--CREATE TABLE DBO.TB_CLIENTE
--(
--	ID_CLIENTE		INT PRIMARY KEY IDENTITY,
--	DOCUMENTO		VARCHAR(14),
--	NOME			VARCHAR(500),
--	TP_PESSOA		VARCHAR(2),
--	ID_ENDERECO		INT,
--	ID_CONTATO		INT,
--	FL_ATIVO		BIT
--)
--GO

--CREATE TABLE DBO.TB_CONTRATO
--(
--	ID_CONTRATO			INT PRIMARY KEY IDENTITY,
--	ID_CLIENTE			INT,
--	ID_EQUIPAMENTO		INT,
--	VL_TARIFA			DECIMAL(18,2),
--	VL_CONSUMO_MINIMO	DECIMAL(18,2),
--	DS_CADENCIA_FIXA	VARCHAR(6),
--	DS_CADENCIA_MOVEL	VARCHAR(6),
--	DT_CONTRATO			DATETIME,
--	DIA_VENCIMENTO		INT,
--	VL_INSTALACAO		DECIMAL(18,2),
--	ID_PRAZO_CONTRATUAL	INT,
--	ID_VENDEDOR			INT
--)
--GO


--ALTER TABLE TB_VENDEDORES
--ADD CONSTRAINT FK_VENDEDORES_ENDERECO FOREIGN KEY (ID_ENDERECO) 
--    REFERENCES TB_ENDERECO (ID_ENDERECO) 
    
--ALTER TABLE TB_VENDEDORES
--ADD CONSTRAINT FK_VENDEDORES_CONTATO FOREIGN KEY (ID_CONTATO) 
--    REFERENCES TB_CONTATO (ID_CONTATO) 
    
--ALTER TABLE TB_VENDEDORES
--ADD CONSTRAINT FK_VENDEDORES_TIPO FOREIGN KEY (TP_VENDEDOR) 
--    REFERENCES TB_TIPO_VENDEDORES (ID_TIPO_VENDEDOR) 

--ALTER TABLE TB_CLIENTE
--ADD CONSTRAINT FK_CLIENTE_ENDERECO FOREIGN KEY (ID_ENDERECO) 
--    REFERENCES TB_ENDERECO (ID_ENDERECO) 

--ALTER TABLE TB_CLIENTE
--ADD CONSTRAINT FK_CLIENTE_CONTATO FOREIGN KEY (ID_CONTATO) 
--    REFERENCES TB_CONTATO (ID_CONTATO) 

--ALTER TABLE TB_CONTRATO
--ADD CONSTRAINT FK_CONTRATO_EQUIPAMENTO FOREIGN KEY (ID_EQUIPAMENTO) 
--    REFERENCES TB_EQUIPAMENTOS (ID_EQUIPAMENTO) 

--ALTER TABLE TB_CONTRATO
--ADD CONSTRAINT FK_PRAZO_CONTRATUAL FOREIGN KEY (ID_PRAZO_CONTRATUAL) 
--    REFERENCES TB_PRAZO_CONTRATUAL (ID_PRAZO_CONTRATUAL) 
    
--ALTER TABLE TB_CONTRATO
--ADD CONSTRAINT FK_CONTRATO_CLIENTE FOREIGN KEY (ID_CLIENTE) 
--    REFERENCES TB_CLIENTE (ID_CLIENTE) 

--ALTER TABLE TB_CONTRATO
--ADD CONSTRAINT FK_CONTRATO_VENDEDOR FOREIGN KEY (ID_VENDEDOR) 
--    REFERENCES TB_VENDEDORES (ID_VENDEDOR) 

--ALTER TABLE TB_EQUIPES
--ADD CONSTRAINT FK_CONTRATO_VENDEDOR FOREIGN KEY (ID_VENDEDOR) 
--    REFERENCES TB_VENDEDORES (ID_VENDEDOR) 

--ALTER TABLE TB_EQUIPES
--ADD CONSTRAINT FK_CONTRATO_CANAL FOREIGN KEY (ID_CANAL) 
--    REFERENCES TB_VENDEDORES (ID_VENDEDOR) 

--ALTER TABLE TB_CLIENTE
--ADD CONSTRAINT UK_DOCUMENTO_CLIENTE UNIQUE (DOCUMENTO)

--ALTER TABLE TB_VENDEDORES
--ADD CONSTRAINT UK_DOCUMENTO_VENDEDORES UNIQUE (DOCUMENTO)