use B2BSolution
go

GRANT EXECUTE ON SPR_VENDEDORES_SELECIONAR TO b2bsolution
GO

GRANT EXECUTE ON SPR_EQUIPAMENTOS_SELECIONAR TO b2bsolution
GO

GRANT EXECUTE ON SPR_EQUIPAMENTOS_INSERIR TO b2bsolution
GO

GRANT EXECUTE ON SPR_ENDERECO_INSERIR TO b2bsolution
GO

GRANT EXECUTE ON SPR_CONTATO_INSERIR TO b2bsolution
GO

GRANT EXECUTE ON SPR_EQUIPES_INSERIR TO b2bsolution
GO

GRANT EXECUTE ON SPR_VENDEDORES_INSERIR TO b2bsolution
GO

GRANT EXECUTE ON SPR_CLIENTE_INSERIR TO b2bsolution
GO

GRANT EXECUTE ON SPR_CONTRATO_INSERIR TO b2bsolution
GO

GRANT EXECUTE ON SPR_CLIENTE_ALTERAR TO b2bsolution
GO

GRANT EXECUTE ON SPR_ENDERECO_ALTERAR TO b2bsolution
GO

GRANT EXECUTE ON SPR_CONTATO_ALTERAR TO b2bsolution
GO

GRANT EXECUTE ON SPR_CLIENTE_SELECIONAR TO b2bsolution
GO
