USE B2BSolution
GO

IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'SPR_CLIENTE_SELECIONAR')
	DROP PROC DBO.SPR_CLIENTE_SELECIONAR
GO
 
CREATE PROC DBO.SPR_CLIENTE_SELECIONAR
(
	@DOCUMENTO		VARCHAR(14) = NULL
)
AS
BEGIN

 	 SELECT C.ID_CLIENTE,
			C.NOME,
			C.TP_PESSOA,
			C.ID_ENDERECO,
			C.ID_CONTATO,
			C.FL_ATIVO,
			C.DOCUMENTO,
		
			E.ID_ENDERECO,
			E.RUA,
			E.NUMERO,
			E.COMPLEMENTO,
			E.CEP,
			E.BAIRRO,
			E.CIDADE,
			E.ESTADO,
	
			CO.ID_CONTATO,
			CO.NOME AS NOME_CONTATO,
			CO.EMAIL,
			CO.TELEFONE,
			CO.CELULAR
	   FROM TB_CLIENTE C
		    INNER JOIN TB_ENDERECO E ON
					   C.ID_ENDERECO = E.ID_ENDERECO
		    INNER JOIN TB_CONTATO CO ON
					   C.ID_CONTATO = CO.ID_CONTATO
	  WHERE C.DOCUMENTO = ISNULL(@DOCUMENTO, C.DOCUMENTO)

END
GO

IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'SPR_EQUIPAMENTOS_SELECIONAR')
	DROP PROC DBO.SPR_EQUIPAMENTOS_SELECIONAR
GO

CREATE PROC DBO.SPR_EQUIPAMENTOS_SELECIONAR
AS
BEGIN

	 SELECT ID_EQUIPAMENTO,
			MARCA,
			MODELO,
			NUMERO_SERIE
	   FROM TB_EQUIPAMENTOS

END
GO


