USE B2BSOLUTION
GO

IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'SPR_EQUIPAMENTOS_INSERIR')
	DROP PROC DBO.SPR_EQUIPAMENTOS_INSERIR
GO

CREATE PROC DBO.SPR_EQUIPAMENTOS_INSERIR
(
	@MARCA			VARCHAR(200),
	@MODELO			VARCHAR(200),
	@NUMERO_SERIE	VARCHAR(200)
)
AS
BEGIN

	 INSERT INTO TB_EQUIPAMENTOS
	 (MARCA, MODELO, NUMERO_SERIE)
	 VALUES
	 (@MARCA, @MODELO, @NUMERO_SERIE)
	 
	 SELECT @@IDENTITY

END
GO

IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'SPR_ENDERECO_INSERIR')
	DROP PROC DBO.SPR_ENDERECO_INSERIR
GO

CREATE PROC DBO.SPR_ENDERECO_INSERIR
(
	@RUA			VARCHAR(200),
	@NUMERO			VARCHAR(6),
	@COMPLEMENTO	VARCHAR(50) = NULL,
	@CEP			VARCHAR(8),
	@BAIRRO			VARCHAR(100),
	@CIDADE			VARCHAR(50),
	@ESTADO			VARCHAR(2)
)
AS
BEGIN

	INSERT INTO TB_ENDERECO
	(RUA, NUMERO, COMPLEMENTO, CEP, BAIRRO, CIDADE, ESTADO)
	VALUES
	(@RUA, @NUMERO, @COMPLEMENTO, @CEP, @BAIRRO, @CIDADE, @ESTADO)
	
	SELECT @@IDENTITY	 

END
GO

IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'SPR_EQUIPES_INSERIR')
	DROP PROC DBO.SPR_EQUIPES_INSERIR
GO

CREATE PROC DBO.SPR_EQUIPES_INSERIR
(
	@ID_VENDEDOR	INT,
	@ID_CANAL		INT
)
AS
BEGIN

	INSERT INTO TB_EQUIPES
	(ID_VENDEDOR, ID_CANAL)
	VALUES
	(@ID_VENDEDOR, @ID_CANAL)
	
	SELECT @@IDENTITY	 

END
GO

IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'SPR_CLIENTE_INSERIR')
	DROP PROC DBO.SPR_CLIENTE_INSERIR
GO

CREATE PROC DBO.SPR_CLIENTE_INSERIR
(
	@NOME			VARCHAR	(500),
	@TP_PESSOA		VARCHAR	(2),
	@ID_ENDERECO	INT,
	@ID_CONTATO		INT,
	@FL_ATIVO		BIT,
	@DOCUMENTO		VARCHAR(14)
)
AS
BEGIN

	INSERT INTO TB_CLIENTE
	(NOME, TP_PESSOA, ID_ENDERECO, ID_CONTATO, FL_ATIVO, DOCUMENTO)
	VALUES
	(@NOME, @TP_PESSOA, @ID_ENDERECO, @ID_CONTATO, @FL_ATIVO, @DOCUMENTO)
	
	SELECT @@IDENTITY	 

END
GO

