USE [B2BSolution]
GO

/****** Object:  StoredProcedure [dbo].[SPR_CONTATO_ALTERAR]    Script Date: 11/12/2015 17:54:28 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SPR_CONTATO_ALTERAR]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[SPR_CONTATO_ALTERAR]
GO

USE [B2BSolution]
GO

/****** Object:  StoredProcedure [dbo].[SPR_CONTATO_ALTERAR]    Script Date: 11/12/2015 17:54:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[SPR_CONTATO_ALTERAR]
(
	@ID_CONTATO		INT,
	@NOME			VARCHAR(100),
	@EMAIL			VARCHAR	(200),
	@TELEFONE		VARCHAR	(10),
	@CELULAR		VARCHAR	(11)
)
AS
BEGIN

	UPDATE TB_CONTATO
	   SET NOME = @NOME, 
		   EMAIL = @EMAIL, 
		   TELEFONE = @TELEFONE, 
		   CELULAR = @CELULAR
	 WHERE ID_CONTATO = @ID_CONTATO

END

GO


