USE [B2BSolution]
GO

/****** Object:  StoredProcedure [dbo].[SPR_VENDEDORES_ALTERAR]    Script Date: 11/12/2015 17:57:36 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SPR_VENDEDORES_ALTERAR]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[SPR_VENDEDORES_ALTERAR]
GO

USE [B2BSolution]
GO

/****** Object:  StoredProcedure [dbo].[SPR_VENDEDORES_ALTERAR]    Script Date: 11/12/2015 17:57:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[SPR_VENDEDORES_ALTERAR]
(
	@ID_VENDEDOR	INT,
	@ID_ENDERECO	INT,
	@ID_CONTATO		INT,
	@DOCUMENTO		VARCHAR(14),
	@COMISSAO		DECIMAL(4,2),
	@TP_VENDEDOR	INT,
	@FL_ATIVO		BIT,
	@NOME			VARCHAR(500),
	@ID_SUPERIOR	INT
)
AS
BEGIN

	UPDATE TB_VENDEDORES
	   SET ID_ENDERECO	= @ID_ENDERECO,
		   ID_CONTATO	= @ID_CONTATO,
		   DOCUMENTO	= @DOCUMENTO,
		   COMISSAO	= @COMISSAO,
		   TP_VENDEDOR	= @TP_VENDEDOR,
		   FL_ATIVO	= @FL_ATIVO,
		   NOME		= @NOME,
		   ID_SUPERIOR	= @ID_SUPERIOR
	 WHERE ID_VENDEDOR = @ID_VENDEDOR

END

GO


