USE [B2BSolution]
GO

/****** Object:  StoredProcedure [dbo].[SPR_ENDERECO_INSERIR]    Script Date: 11/12/2015 17:55:46 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SPR_ENDERECO_INSERIR]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[SPR_ENDERECO_INSERIR]
GO

USE [B2BSolution]
GO

/****** Object:  StoredProcedure [dbo].[SPR_ENDERECO_INSERIR]    Script Date: 11/12/2015 17:55:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROC [dbo].[SPR_ENDERECO_INSERIR]
(
	@RUA			VARCHAR(200),
	@NUMERO			VARCHAR(6),
	@COMPLEMENTO	VARCHAR(50) = NULL,
	@CEP			VARCHAR(8),
	@BAIRRO			VARCHAR(100),
	@CIDADE			VARCHAR(50),
	@ESTADO			VARCHAR(2)
)
AS
BEGIN

	INSERT INTO TB_ENDERECO
	(RUA, NUMERO, COMPLEMENTO, CEP, BAIRRO, CIDADE, ESTADO)
	VALUES
	(@RUA, @NUMERO, @COMPLEMENTO, @CEP, @BAIRRO, @CIDADE, @ESTADO)
	
	SELECT @@IDENTITY	 

END

GO


