USE [B2BSolution]
GO

/****** Object:  StoredProcedure [dbo].[SPR_CLIENTE_SELECIONAR]    Script Date: 11/12/2015 17:54:15 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SPR_CLIENTE_SELECIONAR]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[SPR_CLIENTE_SELECIONAR]
GO

USE [B2BSolution]
GO

/****** Object:  StoredProcedure [dbo].[SPR_CLIENTE_SELECIONAR]    Script Date: 11/12/2015 17:54:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[SPR_CLIENTE_SELECIONAR]
(
	@DOCUMENTO		VARCHAR(14) = NULL
)
AS
BEGIN

 	 SELECT C.ID_CLIENTE,
			C.NOME,
			C.TP_PESSOA,
			C.ID_ENDERECO,
			C.ID_CONTATO,
			C.FL_ATIVO,
			C.DOCUMENTO,
		
			E.ID_ENDERECO,
			E.RUA,
			E.NUMERO,
			E.COMPLEMENTO,
			E.CEP,
			E.BAIRRO,
			E.CIDADE,
			E.ESTADO,
	
			CO.ID_CONTATO,
			CO.NOME AS NOME_CONTATO,
			CO.EMAIL,
			CO.TELEFONE,
			CO.CELULAR
	   FROM TB_CLIENTE C
		    INNER JOIN TB_ENDERECO E ON
					   C.ID_ENDERECO = E.ID_ENDERECO
		    INNER JOIN TB_CONTATO CO ON
					   C.ID_CONTATO = CO.ID_CONTATO
	  WHERE C.DOCUMENTO = ISNULL(@DOCUMENTO, C.DOCUMENTO)

END
GO


