USE [B2BSolution]
GO

/****** Object:  StoredProcedure [dbo].[SPR_PAGAMENTO_INSERIR]    Script Date: 11/12/2015 17:57:14 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SPR_PAGAMENTO_INSERIR]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[SPR_PAGAMENTO_INSERIR]
GO

USE [B2BSolution]
GO

/****** Object:  StoredProcedure [dbo].[SPR_PAGAMENTO_INSERIR]    Script Date: 11/12/2015 17:57:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[SPR_PAGAMENTO_INSERIR]
(
	@DT_PAGAMENTO	DATETIME = NULL,
	@VL_GASTO		DECIMAL(18,2) = NULL,
	@VL_PAGO		DECIMAL(18,2) = NULL,
	@ID_CONTRATO	INT = NULL,
	@FL_PAGO		BIT = NULL
)
AS
BEGIN

	INSERT INTO TB_PAGAMENTO
	(DT_PAGAMENTO, VL_GASTO, VL_PAGO, ID_CONTRATO, FL_PAGO)
	values
	(@DT_PAGAMENTO, @VL_GASTO, @VL_PAGO, @ID_CONTRATO, @FL_PAGO)

	SELECT @@IDENTITY

END
GO


