USE [B2BSolution]
GO

/****** Object:  StoredProcedure [dbo].[SPR_EQUIPAMENTOS_INSERIR]    Script Date: 11/12/2015 17:55:56 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SPR_EQUIPAMENTOS_INSERIR]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[SPR_EQUIPAMENTOS_INSERIR]
GO

USE [B2BSolution]
GO

/****** Object:  StoredProcedure [dbo].[SPR_EQUIPAMENTOS_INSERIR]    Script Date: 11/12/2015 17:55:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROC [dbo].[SPR_EQUIPAMENTOS_INSERIR]
(
	@MARCA			VARCHAR(200),
	@MODELO			VARCHAR(200),
	@NUMERO_SERIE	VARCHAR(200)
)
AS
BEGIN

	 INSERT INTO TB_EQUIPAMENTOS
	 (MARCA, MODELO, NUMERO_SERIE)
	 VALUES
	 (@MARCA, @MODELO, @NUMERO_SERIE)
	 
	 SELECT @@IDENTITY

END

GO


