USE B2BSOLUTION
GO

IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'SPR_VENDEDORES_INSERIR')
	DROP PROC DBO.SPR_VENDEDORES_INSERIR
GO

CREATE PROC DBO.SPR_VENDEDORES_INSERIR
(
	@ID_ENDERECO	INT,
	@ID_CONTATO		INT,
	@DOCUMENTO		VARCHAR(14),
	@COMISSAO		DECIMAL(4,2),
	@TP_VENDEDOR	INT,
	@FL_ATIVO		BIT,
	@NOME			VARCHAR(500),
	@ID_SUPERIOR	INT
)
AS
BEGIN

	INSERT INTO TB_VENDEDORES
	(ID_ENDERECO, ID_CONTATO, DOCUMENTO, COMISSAO, TP_VENDEDOR, FL_ATIVO, NOME, ID_SUPERIOR)
	VALUES
	(@ID_ENDERECO, @ID_CONTATO, @DOCUMENTO, @COMISSAO, @TP_VENDEDOR, @FL_ATIVO, @NOME, @ID_SUPERIOR)
	
	SELECT @@IDENTITY	 

END
GO