USE B2BSOLUTION
GO

IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'SPR_PAGAMENTO_INSERIR')
	DROP PROC DBO.SPR_PAGAMENTO_INSERIR
GO

CREATE PROC DBO.SPR_PAGAMENTO_INSERIR
(
	@DT_PAGAMENTO	DATETIME = NULL,
	@VL_GASTO		DECIMAL(18,2) = NULL,
	@VL_PAGO		DECIMAL(18,2) = NULL,
	@ID_CONTRATO	INT = NULL,
	@FL_PAGO		BIT = NULL
)
AS
BEGIN

	INSERT INTO TB_PAGAMENTO
	(DT_PAGAMENTO, VL_GASTO, VL_PAGO, ID_CONTRATO, FL_PAGO)
	values
	(@DT_PAGAMENTO, @VL_GASTO, @VL_PAGO, @ID_CONTRATO, @FL_PAGO)

	SELECT @@IDENTITY

END