USE B2BSOLUTION
GO

IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'SPR_CONTATO_INSERIR')
	DROP PROC DBO.SPR_CONTATO_INSERIR
GO

CREATE PROC DBO.SPR_CONTATO_INSERIR
(
	@NOME			VARCHAR(100),
	@EMAIL			VARCHAR	(200),
	@TELEFONE		VARCHAR	(10),
	@CELULAR		VARCHAR	(11)
)
AS
BEGIN

	INSERT INTO TB_CONTATO
	(NOME, EMAIL, TELEFONE, CELULAR)
	VALUES
	(@NOME, @EMAIL, @TELEFONE, @CELULAR)
	
	SELECT @@IDENTITY	 

END
GO