USE [B2BSolution]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_CLIENTE_CONTATO]') AND parent_object_id = OBJECT_ID(N'[dbo].[TB_CLIENTE]'))
ALTER TABLE [dbo].[TB_CLIENTE] DROP CONSTRAINT [FK_CLIENTE_CONTATO]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_CLIENTE_ENDERECO]') AND parent_object_id = OBJECT_ID(N'[dbo].[TB_CLIENTE]'))
ALTER TABLE [dbo].[TB_CLIENTE] DROP CONSTRAINT [FK_CLIENTE_ENDERECO]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TB_CLIENT__DOCUM__412EB0B6]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TB_CLIENTE] DROP CONSTRAINT [DF__TB_CLIENT__DOCUM__412EB0B6]
END

GO

USE [B2BSolution]
GO

/****** Object:  Table [dbo].[TB_CLIENTE]    Script Date: 11/12/2015 17:58:49 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_CLIENTE]') AND type in (N'U'))
DROP TABLE [dbo].[TB_CLIENTE]
GO

USE [B2BSolution]
GO

/****** Object:  Table [dbo].[TB_CLIENTE]    Script Date: 11/12/2015 17:58:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TB_CLIENTE](
	[ID_CLIENTE] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](500) NULL,
	[TP_PESSOA] [varchar](2) NULL,
	[ID_ENDERECO] [int] NULL,
	[ID_CONTATO] [int] NULL,
	[fl_ativo] [bit] NULL,
	[DOCUMENTO] [varchar](14) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_CLIENTE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TB_CLIENTE]  WITH CHECK ADD  CONSTRAINT [FK_CLIENTE_CONTATO] FOREIGN KEY([ID_CONTATO])
REFERENCES [dbo].[TB_CONTATO] ([ID_CONTATO])
GO

ALTER TABLE [dbo].[TB_CLIENTE] CHECK CONSTRAINT [FK_CLIENTE_CONTATO]
GO

ALTER TABLE [dbo].[TB_CLIENTE]  WITH CHECK ADD  CONSTRAINT [FK_CLIENTE_ENDERECO] FOREIGN KEY([ID_ENDERECO])
REFERENCES [dbo].[TB_ENDERECO] ([ID_ENDERECO])
GO

ALTER TABLE [dbo].[TB_CLIENTE] CHECK CONSTRAINT [FK_CLIENTE_ENDERECO]
GO

ALTER TABLE [dbo].[TB_CLIENTE] ADD  DEFAULT ('11111111') FOR [DOCUMENTO]
GO


