USE [B2BSolution]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_CONTRATO_CLIENTE]') AND parent_object_id = OBJECT_ID(N'[dbo].[TB_CONTRATO]'))
ALTER TABLE [dbo].[TB_CONTRATO] DROP CONSTRAINT [FK_CONTRATO_CLIENTE]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_CONTRATO_EQUIPAMENTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[TB_CONTRATO]'))
ALTER TABLE [dbo].[TB_CONTRATO] DROP CONSTRAINT [FK_CONTRATO_EQUIPAMENTO]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_CONTRATO_VENDEDOR]') AND parent_object_id = OBJECT_ID(N'[dbo].[TB_CONTRATO]'))
ALTER TABLE [dbo].[TB_CONTRATO] DROP CONSTRAINT [FK_CONTRATO_VENDEDOR]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TB_CONTRA__VL_TA__6477ECF3]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TB_CONTRATO] DROP CONSTRAINT [DF__TB_CONTRA__VL_TA__6477ECF3]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TB_CONTRA__VL_TA__656C112C]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TB_CONTRATO] DROP CONSTRAINT [DF__TB_CONTRA__VL_TA__656C112C]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TB_CONTRA__VL_TA__66603565]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TB_CONTRATO] DROP CONSTRAINT [DF__TB_CONTRA__VL_TA__66603565]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TB_CONTRA__VL_TA__6754599E]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TB_CONTRATO] DROP CONSTRAINT [DF__TB_CONTRA__VL_TA__6754599E]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TB_CONTRA__VL_TA__68487DD7]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TB_CONTRATO] DROP CONSTRAINT [DF__TB_CONTRA__VL_TA__68487DD7]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TB_CONTRA__VL_ME__6A30C649]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TB_CONTRATO] DROP CONSTRAINT [DF__TB_CONTRA__VL_ME__6A30C649]
END

GO

USE [B2BSolution]
GO

/****** Object:  Table [dbo].[TB_CONTRATO]    Script Date: 11/12/2015 17:59:31 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_CONTRATO]') AND type in (N'U'))
DROP TABLE [dbo].[TB_CONTRATO]
GO

USE [B2BSolution]
GO

/****** Object:  Table [dbo].[TB_CONTRATO]    Script Date: 11/12/2015 17:59:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TB_CONTRATO](
	[ID_CONTRATO] [int] IDENTITY(1,1) NOT NULL,
	[ID_CLIENTE] [int] NULL,
	[ID_EQUIPAMENTO] [int] NULL,
	[VL_CONSUMO_MINIMO] [decimal](18, 2) NULL,
	[DS_CADENCIA_FIXA] [varchar](6) NULL,
	[DS_CADENCIA_MOVEL] [varchar](6) NULL,
	[DT_CONTRATO] [datetime] NULL,
	[DIA_VENCIMENTO] [int] NULL,
	[VL_INSTALACAO] [decimal](18, 2) NULL,
	[ID_PRAZO_CONTRATUAL] [int] NULL,
	[ID_VENDEDOR] [int] NULL,
	[VL_TARIFA_LOCAL] [decimal](18, 2) NOT NULL,
	[VL_TARIFA_LDN] [decimal](18, 2) NOT NULL,
	[VL_TARIFA_VC1] [decimal](18, 2) NOT NULL,
	[VL_TARIFA_VC2] [decimal](18, 2) NOT NULL,
	[VL_TARIFA_VC3] [decimal](18, 2) NOT NULL,
	[VL_MENSALIDADE] [decimal](18, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_CONTRATO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TB_CONTRATO]  WITH CHECK ADD  CONSTRAINT [FK_CONTRATO_CLIENTE] FOREIGN KEY([ID_CLIENTE])
REFERENCES [dbo].[TB_CLIENTE] ([ID_CLIENTE])
GO

ALTER TABLE [dbo].[TB_CONTRATO] CHECK CONSTRAINT [FK_CONTRATO_CLIENTE]
GO

ALTER TABLE [dbo].[TB_CONTRATO]  WITH CHECK ADD  CONSTRAINT [FK_CONTRATO_EQUIPAMENTO] FOREIGN KEY([ID_EQUIPAMENTO])
REFERENCES [dbo].[TB_EQUIPAMENTOS] ([ID_EQUIPAMENTO])
GO

ALTER TABLE [dbo].[TB_CONTRATO] CHECK CONSTRAINT [FK_CONTRATO_EQUIPAMENTO]
GO

ALTER TABLE [dbo].[TB_CONTRATO]  WITH CHECK ADD  CONSTRAINT [FK_CONTRATO_VENDEDOR] FOREIGN KEY([ID_VENDEDOR])
REFERENCES [dbo].[TB_VENDEDORES] ([ID_VENDEDOR])
GO

ALTER TABLE [dbo].[TB_CONTRATO] CHECK CONSTRAINT [FK_CONTRATO_VENDEDOR]
GO

ALTER TABLE [dbo].[TB_CONTRATO] ADD  DEFAULT ((0)) FOR [VL_TARIFA_LOCAL]
GO

ALTER TABLE [dbo].[TB_CONTRATO] ADD  DEFAULT ((0)) FOR [VL_TARIFA_LDN]
GO

ALTER TABLE [dbo].[TB_CONTRATO] ADD  DEFAULT ((0)) FOR [VL_TARIFA_VC1]
GO

ALTER TABLE [dbo].[TB_CONTRATO] ADD  DEFAULT ((0)) FOR [VL_TARIFA_VC2]
GO

ALTER TABLE [dbo].[TB_CONTRATO] ADD  DEFAULT ((0)) FOR [VL_TARIFA_VC3]
GO

ALTER TABLE [dbo].[TB_CONTRATO] ADD  DEFAULT ((0)) FOR [VL_MENSALIDADE]
GO


