USE [B2BSolution]
GO

/****** Object:  Table [dbo].[TB_PRAZO_CONTRATUAL]    Script Date: 11/12/2015 18:00:18 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_PRAZO_CONTRATUAL]') AND type in (N'U'))
DROP TABLE [dbo].[TB_PRAZO_CONTRATUAL]
GO

USE [B2BSolution]
GO

/****** Object:  Table [dbo].[TB_PRAZO_CONTRATUAL]    Script Date: 11/12/2015 18:00:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TB_PRAZO_CONTRATUAL](
	[ID_PRAZO_CONTRATUAL] [int] IDENTITY(1,1) NOT NULL,
	[PERIODO] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_PRAZO_CONTRATUAL] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


INSERT INTO TB_PRAZO_CONTRATUAL VALUES ('6 Meses')
INSERT INTO TB_PRAZO_CONTRATUAL VALUES ('12 Meses')
INSERT INTO TB_PRAZO_CONTRATUAL VALUES ('24 Meses')
INSERT INTO TB_PRAZO_CONTRATUAL VALUES ('Indetermidado')