use B2BSolution
go

IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'SPR_CONTRATO_ALTERAR')
	DROP PROC DBO.SPR_CONTRATO_ALTERAR
GO

CREATE PROC DBO.SPR_CONTRATO_ALTERAR
(
	@ID_CONTRATO		int,
	@ID_CLIENTE			int,
	@ID_EQUIPAMENTO		int = NULL,
	@VL_TARIFA_LOCAL	DECIMAL(18,2),
	@VL_TARIFA_LDN		DECIMAL(18,2),
	@VL_TARIFA_VC1		DECIMAL(18,2),
	@VL_TARIFA_VC2		DECIMAL(18,2),
	@VL_TARIFA_VC3		DECIMAL(18,2),
	@VL_CONSUMO_MINIMO	decimal(18,2),
	@DS_CADENCIA_FIXA	VARCHAR(6),
	@DS_CADENCIA_MOVEL	VARCHAR(6),
	@DT_CONTRATO		datetime,
	@DIA_VENCIMENTO		int,
	@VL_INSTALACAO		decimal(18,2)  = NULL,
	@ID_PRAZO_CONTRATUAL int,
	@ID_VENDEDOR		 int
)
AS
BEGIN

	UPDATE TB_CONTRATO
	   SET ID_CLIENTE = @ID_CLIENTE,
		   ID_EQUIPAMENTO = @ID_EQUIPAMENTO,
		   VL_TARIFA_LOCAL = @VL_TARIFA_LOCAL,
		   VL_TARIFA_LDN = @VL_TARIFA_LDN,
		   VL_TARIFA_VC1 = @VL_TARIFA_VC1,
		   VL_TARIFA_VC2 = @VL_TARIFA_VC2,
		   VL_TARIFA_VC3 = @VL_TARIFA_VC3,
		   VL_CONSUMO_MINIMO = @VL_CONSUMO_MINIMO,
		   DT_CONTRATO = @DT_CONTRATO,
		   DS_CADENCIA_FIXA = @DS_CADENCIA_FIXA,
		   DS_CADENCIA_MOVEL = @DS_CADENCIA_MOVEL,
		   DIA_VENCIMENTO = @DIA_VENCIMENTO,
		   VL_INSTALACAO = @VL_INSTALACAO,
		   ID_PRAZO_CONTRATUAL = @ID_PRAZO_CONTRATUAL,
		   ID_VENDEDOR = @ID_VENDEDOR
	 WHERE ID_CONTRATO = @ID_CONTRATO

END
GO
