use B2BSolution
go

IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'SPR_CLIENTE_ALTERAR')
	DROP PROC DBO.SPR_CLIENTE_ALTERAR
GO

CREATE PROC DBO.SPR_CLIENTE_ALTERAR
(
	@ID_CLIENTE		INT,
	@NOME			VARCHAR	(500),
	@TP_PESSOA		VARCHAR	(2),
	@ID_ENDERECO	INT,
	@ID_CONTATO		INT,
	@FL_ATIVO		BIT
)
AS
BEGIN

	UPDATE TB_CLIENTE
	   SET NOME = @NOME,
		   TP_PESSOA = @TP_PESSOA,
		   ID_ENDERECO = @ID_ENDERECO,
		   ID_CONTATO = @ID_CONTATO,
		   FL_ATIVO = @FL_ATIVO	   
	 WHERE ID_CLIENTE = @ID_CLIENTE
	 
END