use B2BSolution
go

IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'SPR_ENDERECO_ALTERAR')
	DROP PROC DBO.SPR_ENDERECO_ALTERAR
GO

CREATE PROC DBO.SPR_ENDERECO_ALTERAR
(
	@ID_ENDERECO	INT,
	@RUA			VARCHAR(200),
	@NUMERO			VARCHAR(6),
	@COMPLEMENTO	VARCHAR(50) = NULL,
	@CEP			VARCHAR(8),
	@BAIRRO			VARCHAR(100),
	@CIDADE			VARCHAR(50),
	@ESTADO			VARCHAR(2)
)
AS
BEGIN

	UPDATE TB_ENDERECO
	   SET RUA = @RUA,
		   NUMERO = @NUMERO,
		   COMPLEMENTO = @COMPLEMENTO,
		   CEP = @CEP,
		   BAIRRO = @BAIRRO,
		   CIDADE = @CIDADE,
		   ESTADO = @ESTADO
	 WHERE ID_ENDERECO = @ID_ENDERECO
	 
END
GO