use B2BSolution
go

IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'SPR_VENDEDORES_ALTERAR')
	DROP PROC DBO.SPR_VENDEDORES_ALTERAR
GO

CREATE PROC DBO.SPR_VENDEDORES_ALTERAR
(
	@ID_VENDEDOR	INT,
	@ID_ENDERECO	INT,
	@ID_CONTATO		INT,
	@DOCUMENTO		VARCHAR(14),
	@COMISSAO		DECIMAL(4,2),
	@TP_VENDEDOR	INT,
	@FL_ATIVO		BIT,
	@NOME			VARCHAR(500),
	@ID_SUPERIOR	INT
)
AS
BEGIN

	UPDATE TB_VENDEDORES
	   SET ID_ENDERECO	= @ID_ENDERECO,
		   ID_CONTATO	= @ID_CONTATO,
		   DOCUMENTO	= @DOCUMENTO,
		   COMISSAO	= @COMISSAO,
		   TP_VENDEDOR	= @TP_VENDEDOR,
		   FL_ATIVO	= @FL_ATIVO,
		   NOME		= @NOME,
		   ID_SUPERIOR	= @ID_SUPERIOR
	 WHERE ID_VENDEDOR = @ID_VENDEDOR

END
GO
