use B2BSolution
go

IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'SPR_PAGAMENTO_ALTERAR')
	DROP PROC DBO.SPR_PAGAMENTO_ALTERAR
GO

CREATE PROC DBO.SPR_PAGAMENTO_ALTERAR
(
	@ID_PAGAMENTO	INT	= NULL,
	@FL_PAGO		BIT
)
AS
BEGIN

	UPDATE TB_PAGAMENTO
	   SET FL_PAGO = @FL_PAGO
	 WHERE ID_PAGAMENTO = @ID_PAGAMENTO

END