use B2BSolution
go

IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'SPR_CONTATO_ALTERAR')
	DROP PROC DBO.SPR_CONTATO_ALTERAR
GO

CREATE PROC DBO.SPR_CONTATO_ALTERAR
(
	@ID_CONTATO		INT,
	@NOME			VARCHAR(100),
	@EMAIL			VARCHAR	(200),
	@TELEFONE		VARCHAR	(10),
	@CELULAR		VARCHAR	(11)
)
AS
BEGIN

	UPDATE TB_CONTATO
	   SET NOME = @NOME, 
		   EMAIL = @EMAIL, 
		   TELEFONE = @TELEFONE, 
		   CELULAR = @CELULAR
	 WHERE ID_CONTATO = @ID_CONTATO

END
GO