USE B2BSolution
GO

IF EXISTS(SELECT * FROM SYS.objects WHERE OBJECT_ID = OBJECT_ID('SPR_PAGAMENTO_SELECIONAR')) 
	DROP PROC DBO.SPR_PAGAMENTO_SELECIONAR
GO

CREATE PROC DBO.SPR_PAGAMENTO_SELECIONAR
(
	@DT_PAGAMENTO	datetime,
	@DOCUMENTO		VARCHAR(14) = NULL
)
AS
BEGIN

	create table #TB_CONTRATO
	(
		ID_CONTRATO			INT,
		VL_TARIFA_LOCAL		decimal(18,2),
		VL_TARIFA_LDN		decimal(18,2),
		VL_TARIFA_VC1		decimal(18,2),
		VL_TARIFA_VC2		decimal(18,2),
		VL_TARIFA_VC3		decimal(18,2),
		VL_CONSUMO_MINIMO	DECIMAL(18,2),
		DS_CADENCIA_FIXA	VARCHAR(6),
		DS_CADENCIA_MOVEL	VARCHAR(6),
		DT_CONTRATO			DATETIME,
		DIA_VENCIMENTO		INT,
		VL_INSTALACAO		DECIMAL(18,2),
		ID_PRAZO_CONTRATUAL	INT,
		ID_VENDEDOR			INT,
		
		ID_CLIENTE		INT,
		DOCUMENTO		VARCHAR(14),
		NOME			VARCHAR(500),
		TP_PESSOA		VARCHAR(2),
		ID_ENDERECO_CLIENTE		INT,
		ID_CONTATO_CLIENTE		INT,
		FL_ATIVO		BIT,
		
		ID_EQUIPAMENTO		INT,
		MARCA				VARCHAR(200),
		MODELO				VARCHAR(200),
		NUMERO_SERIE		VARCHAR(200),
		
		ID_ENDERECO			INT	,
		RUA					VARCHAR(200),
		NUMERO				VARCHAR(6),
		COMPLEMENTO			VARCHAR(50),
		CEP					VARCHAR(8),
		BAIRRO				VARCHAR(100),
		CIDADE				VARCHAR(50),
		ESTADO				VARCHAR(2),
		
		ID_CONTATO			INT,
		NOME_CONTATO		VARCHAR(100),
		EMAIL				VARCHAR(200),
		TELEFONE			VARCHAR(10),
		CELULAR				VARCHAR(11),
		
		ID_VENDEDOR_V		INT,
		ID_ENDERECO_VENDENDOR	INT,
		ID_CONTATO_VENDEDOR		INT,
		DOCUMENTO_VENDEDOR		VARCHAR(14),
		COMISSAO_VENDEDOR		DECIMAL(18,2),
		TP_VENDEDOR				INT,
		FL_ATIVO_VENDEDOR		BIT,
		NOME_VENDEDOR			VARCHAR(500),
		ID_SUPERIOR				INT
	)

	INSERT INTO #TB_CONTRATO
		   EXEC SPR_CONTRATO_SELECIONAR @ID_CLIENTE = @DOCUMENTO
			
	SELECT * 
	  FROM TB_PAGAMENTO PAG
		   INNER JOIN #TB_CONTRATO CONT
				 ON PAG.ID_CONTRATO = CONT.ID_CONTRATO
	 WHERE CONT.DOCUMENTO = ISNULL(@DOCUMENTO, CONT.DOCUMENTO) AND
		   PAG.DT_PAGAMENTO >= @DT_PAGAMENTO

	DROP TABLE #TB_CONTRATO

END