use B2BSolution
go

IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'SPR_PAGAMENTO_DELETAR')
	DROP PROC DBO.SPR_PAGAMENTO_DELETAR
GO

CREATE PROC DBO.SPR_PAGAMENTO_DELETAR
(
	@ID_PAGAMENTO	INT
)
AS
BEGIN

	DELETE FROM TB_PAGAMENTO
	WHERE ID_PAGAMENTO = @ID_PAGAMENTO

END