//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2BSolution.Financeiro.Teste.ArquivoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ArquivoService.IParametroListaOf_Pagamento")]
    public interface IParametroListaOf_Pagamento {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametroListaOf_Pagamento/EntidadeParametro", ReplyAction="http://tempuri.org/IParametroListaOf_Pagamento/EntidadeParametroResponse")]
        void EntidadeParametro(B2BSolution.Financeiro.Entidades.Pagamento[] lista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametroListaOf_Pagamento/EntidadeParametro", ReplyAction="http://tempuri.org/IParametroListaOf_Pagamento/EntidadeParametroResponse")]
        System.Threading.Tasks.Task EntidadeParametroAsync(B2BSolution.Financeiro.Entidades.Pagamento[] lista);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IParametroListaOf_PagamentoChannel : B2BSolution.Financeiro.Teste.ArquivoService.IParametroListaOf_Pagamento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ParametroListaOf_PagamentoClient : System.ServiceModel.ClientBase<B2BSolution.Financeiro.Teste.ArquivoService.IParametroListaOf_Pagamento>, B2BSolution.Financeiro.Teste.ArquivoService.IParametroListaOf_Pagamento {
        
        public ParametroListaOf_PagamentoClient() {
        }
        
        public ParametroListaOf_PagamentoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ParametroListaOf_PagamentoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParametroListaOf_PagamentoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParametroListaOf_PagamentoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void EntidadeParametro(B2BSolution.Financeiro.Entidades.Pagamento[] lista) {
            base.Channel.EntidadeParametro(lista);
        }
        
        public System.Threading.Tasks.Task EntidadeParametroAsync(B2BSolution.Financeiro.Entidades.Pagamento[] lista) {
            return base.Channel.EntidadeParametroAsync(lista);
        }
    }
}
