//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2BSolution.Financeiro.Formulario.VendedoresService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VendedoresService.IInserirOf_Vendedores")]
    public interface IInserirOf_Vendedores {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInserirOf_Vendedores/Incluir", ReplyAction="http://tempuri.org/IInserirOf_Vendedores/IncluirResponse")]
        int Incluir(B2BSolution.Financeiro.Entidades.Vendedores entidades);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInserirOf_Vendedores/Incluir", ReplyAction="http://tempuri.org/IInserirOf_Vendedores/IncluirResponse")]
        System.Threading.Tasks.Task<int> IncluirAsync(B2BSolution.Financeiro.Entidades.Vendedores entidades);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInserirOf_VendedoresChannel : B2BSolution.Financeiro.Formulario.VendedoresService.IInserirOf_Vendedores, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InserirOf_VendedoresClient : System.ServiceModel.ClientBase<B2BSolution.Financeiro.Formulario.VendedoresService.IInserirOf_Vendedores>, B2BSolution.Financeiro.Formulario.VendedoresService.IInserirOf_Vendedores {
        
        public InserirOf_VendedoresClient() {
        }
        
        public InserirOf_VendedoresClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InserirOf_VendedoresClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InserirOf_VendedoresClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InserirOf_VendedoresClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Incluir(B2BSolution.Financeiro.Entidades.Vendedores entidades) {
            return base.Channel.Incluir(entidades);
        }
        
        public System.Threading.Tasks.Task<int> IncluirAsync(B2BSolution.Financeiro.Entidades.Vendedores entidades) {
            return base.Channel.IncluirAsync(entidades);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VendedoresService.IEntidadeOf_Vendedores")]
    public interface IEntidadeOf_Vendedores {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntidadeOf_Vendedores/Entidade", ReplyAction="http://tempuri.org/IEntidadeOf_Vendedores/EntidadeResponse")]
        B2BSolution.Financeiro.Entidades.Vendedores Entidade(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntidadeOf_Vendedores/Entidade", ReplyAction="http://tempuri.org/IEntidadeOf_Vendedores/EntidadeResponse")]
        System.Threading.Tasks.Task<B2BSolution.Financeiro.Entidades.Vendedores> EntidadeAsync(string codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEntidadeOf_VendedoresChannel : B2BSolution.Financeiro.Formulario.VendedoresService.IEntidadeOf_Vendedores, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EntidadeOf_VendedoresClient : System.ServiceModel.ClientBase<B2BSolution.Financeiro.Formulario.VendedoresService.IEntidadeOf_Vendedores>, B2BSolution.Financeiro.Formulario.VendedoresService.IEntidadeOf_Vendedores {
        
        public EntidadeOf_VendedoresClient() {
        }
        
        public EntidadeOf_VendedoresClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EntidadeOf_VendedoresClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EntidadeOf_VendedoresClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EntidadeOf_VendedoresClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public B2BSolution.Financeiro.Entidades.Vendedores Entidade(string codigo) {
            return base.Channel.Entidade(codigo);
        }
        
        public System.Threading.Tasks.Task<B2BSolution.Financeiro.Entidades.Vendedores> EntidadeAsync(string codigo) {
            return base.Channel.EntidadeAsync(codigo);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VendedoresService.IListarTodosOf_Vendedores")]
    public interface IListarTodosOf_Vendedores {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListarTodosOf_Vendedores/ListarTodos", ReplyAction="http://tempuri.org/IListarTodosOf_Vendedores/ListarTodosResponse")]
        B2BSolution.Financeiro.Entidades.Vendedores[] ListarTodos(B2BSolution.Financeiro.Entidades.Vendedores entidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListarTodosOf_Vendedores/ListarTodos", ReplyAction="http://tempuri.org/IListarTodosOf_Vendedores/ListarTodosResponse")]
        System.Threading.Tasks.Task<B2BSolution.Financeiro.Entidades.Vendedores[]> ListarTodosAsync(B2BSolution.Financeiro.Entidades.Vendedores entidade);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IListarTodosOf_VendedoresChannel : B2BSolution.Financeiro.Formulario.VendedoresService.IListarTodosOf_Vendedores, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListarTodosOf_VendedoresClient : System.ServiceModel.ClientBase<B2BSolution.Financeiro.Formulario.VendedoresService.IListarTodosOf_Vendedores>, B2BSolution.Financeiro.Formulario.VendedoresService.IListarTodosOf_Vendedores {
        
        public ListarTodosOf_VendedoresClient() {
        }
        
        public ListarTodosOf_VendedoresClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ListarTodosOf_VendedoresClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListarTodosOf_VendedoresClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListarTodosOf_VendedoresClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public B2BSolution.Financeiro.Entidades.Vendedores[] ListarTodos(B2BSolution.Financeiro.Entidades.Vendedores entidade) {
            return base.Channel.ListarTodos(entidade);
        }
        
        public System.Threading.Tasks.Task<B2BSolution.Financeiro.Entidades.Vendedores[]> ListarTodosAsync(B2BSolution.Financeiro.Entidades.Vendedores entidade) {
            return base.Channel.ListarTodosAsync(entidade);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VendedoresService.IAlterarOf_Vendedores")]
    public interface IAlterarOf_Vendedores {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlterarOf_Vendedores/Alterar", ReplyAction="http://tempuri.org/IAlterarOf_Vendedores/AlterarResponse")]
        void Alterar(B2BSolution.Financeiro.Entidades.Vendedores entidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlterarOf_Vendedores/Alterar", ReplyAction="http://tempuri.org/IAlterarOf_Vendedores/AlterarResponse")]
        System.Threading.Tasks.Task AlterarAsync(B2BSolution.Financeiro.Entidades.Vendedores entidade);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlterarOf_VendedoresChannel : B2BSolution.Financeiro.Formulario.VendedoresService.IAlterarOf_Vendedores, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlterarOf_VendedoresClient : System.ServiceModel.ClientBase<B2BSolution.Financeiro.Formulario.VendedoresService.IAlterarOf_Vendedores>, B2BSolution.Financeiro.Formulario.VendedoresService.IAlterarOf_Vendedores {
        
        public AlterarOf_VendedoresClient() {
        }
        
        public AlterarOf_VendedoresClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlterarOf_VendedoresClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlterarOf_VendedoresClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlterarOf_VendedoresClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Alterar(B2BSolution.Financeiro.Entidades.Vendedores entidade) {
            base.Channel.Alterar(entidade);
        }
        
        public System.Threading.Tasks.Task AlterarAsync(B2BSolution.Financeiro.Entidades.Vendedores entidade) {
            return base.Channel.AlterarAsync(entidade);
        }
    }
}
