//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2BSolution.Financeiro.Teste.ClienteService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClienteService.IEntidadeOf_Cliente")]
    public interface IEntidadeOf_Cliente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntidadeOf_Cliente/Entidade", ReplyAction="http://tempuri.org/IEntidadeOf_Cliente/EntidadeResponse")]
        B2BSolution.Financeiro.Entidades.Cliente Entidade(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntidadeOf_Cliente/Entidade", ReplyAction="http://tempuri.org/IEntidadeOf_Cliente/EntidadeResponse")]
        System.Threading.Tasks.Task<B2BSolution.Financeiro.Entidades.Cliente> EntidadeAsync(string codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEntidadeOf_ClienteChannel : B2BSolution.Financeiro.Teste.ClienteService.IEntidadeOf_Cliente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EntidadeOf_ClienteClient : System.ServiceModel.ClientBase<B2BSolution.Financeiro.Teste.ClienteService.IEntidadeOf_Cliente>, B2BSolution.Financeiro.Teste.ClienteService.IEntidadeOf_Cliente {
        
        public EntidadeOf_ClienteClient() {
        }
        
        public EntidadeOf_ClienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EntidadeOf_ClienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EntidadeOf_ClienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EntidadeOf_ClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public B2BSolution.Financeiro.Entidades.Cliente Entidade(string codigo) {
            return base.Channel.Entidade(codigo);
        }
        
        public System.Threading.Tasks.Task<B2BSolution.Financeiro.Entidades.Cliente> EntidadeAsync(string codigo) {
            return base.Channel.EntidadeAsync(codigo);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClienteService.IAlterarOf_Cliente")]
    public interface IAlterarOf_Cliente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlterarOf_Cliente/Alterar", ReplyAction="http://tempuri.org/IAlterarOf_Cliente/AlterarResponse")]
        void Alterar(B2BSolution.Financeiro.Entidades.Cliente entidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlterarOf_Cliente/Alterar", ReplyAction="http://tempuri.org/IAlterarOf_Cliente/AlterarResponse")]
        System.Threading.Tasks.Task AlterarAsync(B2BSolution.Financeiro.Entidades.Cliente entidade);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlterarOf_ClienteChannel : B2BSolution.Financeiro.Teste.ClienteService.IAlterarOf_Cliente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlterarOf_ClienteClient : System.ServiceModel.ClientBase<B2BSolution.Financeiro.Teste.ClienteService.IAlterarOf_Cliente>, B2BSolution.Financeiro.Teste.ClienteService.IAlterarOf_Cliente {
        
        public AlterarOf_ClienteClient() {
        }
        
        public AlterarOf_ClienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlterarOf_ClienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlterarOf_ClienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlterarOf_ClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Alterar(B2BSolution.Financeiro.Entidades.Cliente entidade) {
            base.Channel.Alterar(entidade);
        }
        
        public System.Threading.Tasks.Task AlterarAsync(B2BSolution.Financeiro.Entidades.Cliente entidade) {
            return base.Channel.AlterarAsync(entidade);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClienteService.IInserirOf_Cliente")]
    public interface IInserirOf_Cliente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInserirOf_Cliente/Incluir", ReplyAction="http://tempuri.org/IInserirOf_Cliente/IncluirResponse")]
        int Incluir(B2BSolution.Financeiro.Entidades.Cliente entidades);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInserirOf_Cliente/Incluir", ReplyAction="http://tempuri.org/IInserirOf_Cliente/IncluirResponse")]
        System.Threading.Tasks.Task<int> IncluirAsync(B2BSolution.Financeiro.Entidades.Cliente entidades);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInserirOf_ClienteChannel : B2BSolution.Financeiro.Teste.ClienteService.IInserirOf_Cliente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InserirOf_ClienteClient : System.ServiceModel.ClientBase<B2BSolution.Financeiro.Teste.ClienteService.IInserirOf_Cliente>, B2BSolution.Financeiro.Teste.ClienteService.IInserirOf_Cliente {
        
        public InserirOf_ClienteClient() {
        }
        
        public InserirOf_ClienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InserirOf_ClienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InserirOf_ClienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InserirOf_ClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Incluir(B2BSolution.Financeiro.Entidades.Cliente entidades) {
            return base.Channel.Incluir(entidades);
        }
        
        public System.Threading.Tasks.Task<int> IncluirAsync(B2BSolution.Financeiro.Entidades.Cliente entidades) {
            return base.Channel.IncluirAsync(entidades);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClienteService.IListarOf_Cliente")]
    public interface IListarOf_Cliente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListarOf_Cliente/Listar", ReplyAction="http://tempuri.org/IListarOf_Cliente/ListarResponse")]
        B2BSolution.Financeiro.Entidades.Cliente[] Listar(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListarOf_Cliente/Listar", ReplyAction="http://tempuri.org/IListarOf_Cliente/ListarResponse")]
        System.Threading.Tasks.Task<B2BSolution.Financeiro.Entidades.Cliente[]> ListarAsync(string codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IListarOf_ClienteChannel : B2BSolution.Financeiro.Teste.ClienteService.IListarOf_Cliente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListarOf_ClienteClient : System.ServiceModel.ClientBase<B2BSolution.Financeiro.Teste.ClienteService.IListarOf_Cliente>, B2BSolution.Financeiro.Teste.ClienteService.IListarOf_Cliente {
        
        public ListarOf_ClienteClient() {
        }
        
        public ListarOf_ClienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ListarOf_ClienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListarOf_ClienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListarOf_ClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public B2BSolution.Financeiro.Entidades.Cliente[] Listar(string codigo) {
            return base.Channel.Listar(codigo);
        }
        
        public System.Threading.Tasks.Task<B2BSolution.Financeiro.Entidades.Cliente[]> ListarAsync(string codigo) {
            return base.Channel.ListarAsync(codigo);
        }
    }
}
