//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2BSolution.Financeiro.Formulario.ContratoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ContratoService.IEntidadeOf_Contrato")]
    public interface IEntidadeOf_Contrato {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntidadeOf_Contrato/Entidade", ReplyAction="http://tempuri.org/IEntidadeOf_Contrato/EntidadeResponse")]
        B2BSolution.Financeiro.Entidades.Contrato Entidade(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntidadeOf_Contrato/Entidade", ReplyAction="http://tempuri.org/IEntidadeOf_Contrato/EntidadeResponse")]
        System.Threading.Tasks.Task<B2BSolution.Financeiro.Entidades.Contrato> EntidadeAsync(string codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEntidadeOf_ContratoChannel : B2BSolution.Financeiro.Formulario.ContratoService.IEntidadeOf_Contrato, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EntidadeOf_ContratoClient : System.ServiceModel.ClientBase<B2BSolution.Financeiro.Formulario.ContratoService.IEntidadeOf_Contrato>, B2BSolution.Financeiro.Formulario.ContratoService.IEntidadeOf_Contrato {
        
        public EntidadeOf_ContratoClient() {
        }
        
        public EntidadeOf_ContratoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EntidadeOf_ContratoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EntidadeOf_ContratoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EntidadeOf_ContratoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public B2BSolution.Financeiro.Entidades.Contrato Entidade(string codigo) {
            return base.Channel.Entidade(codigo);
        }
        
        public System.Threading.Tasks.Task<B2BSolution.Financeiro.Entidades.Contrato> EntidadeAsync(string codigo) {
            return base.Channel.EntidadeAsync(codigo);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ContratoService.IInserirOf_Contrato")]
    public interface IInserirOf_Contrato {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInserirOf_Contrato/Incluir", ReplyAction="http://tempuri.org/IInserirOf_Contrato/IncluirResponse")]
        int Incluir(B2BSolution.Financeiro.Entidades.Contrato entidades);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInserirOf_Contrato/Incluir", ReplyAction="http://tempuri.org/IInserirOf_Contrato/IncluirResponse")]
        System.Threading.Tasks.Task<int> IncluirAsync(B2BSolution.Financeiro.Entidades.Contrato entidades);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInserirOf_ContratoChannel : B2BSolution.Financeiro.Formulario.ContratoService.IInserirOf_Contrato, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InserirOf_ContratoClient : System.ServiceModel.ClientBase<B2BSolution.Financeiro.Formulario.ContratoService.IInserirOf_Contrato>, B2BSolution.Financeiro.Formulario.ContratoService.IInserirOf_Contrato {
        
        public InserirOf_ContratoClient() {
        }
        
        public InserirOf_ContratoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InserirOf_ContratoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InserirOf_ContratoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InserirOf_ContratoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Incluir(B2BSolution.Financeiro.Entidades.Contrato entidades) {
            return base.Channel.Incluir(entidades);
        }
        
        public System.Threading.Tasks.Task<int> IncluirAsync(B2BSolution.Financeiro.Entidades.Contrato entidades) {
            return base.Channel.IncluirAsync(entidades);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ContratoService.IAlterarOf_Contrato")]
    public interface IAlterarOf_Contrato {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlterarOf_Contrato/Alterar", ReplyAction="http://tempuri.org/IAlterarOf_Contrato/AlterarResponse")]
        void Alterar(B2BSolution.Financeiro.Entidades.Contrato entidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlterarOf_Contrato/Alterar", ReplyAction="http://tempuri.org/IAlterarOf_Contrato/AlterarResponse")]
        System.Threading.Tasks.Task AlterarAsync(B2BSolution.Financeiro.Entidades.Contrato entidade);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlterarOf_ContratoChannel : B2BSolution.Financeiro.Formulario.ContratoService.IAlterarOf_Contrato, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlterarOf_ContratoClient : System.ServiceModel.ClientBase<B2BSolution.Financeiro.Formulario.ContratoService.IAlterarOf_Contrato>, B2BSolution.Financeiro.Formulario.ContratoService.IAlterarOf_Contrato {
        
        public AlterarOf_ContratoClient() {
        }
        
        public AlterarOf_ContratoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlterarOf_ContratoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlterarOf_ContratoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlterarOf_ContratoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Alterar(B2BSolution.Financeiro.Entidades.Contrato entidade) {
            base.Channel.Alterar(entidade);
        }
        
        public System.Threading.Tasks.Task AlterarAsync(B2BSolution.Financeiro.Entidades.Contrato entidade) {
            return base.Channel.AlterarAsync(entidade);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ContratoService.IListarTodosOf_Contrato")]
    public interface IListarTodosOf_Contrato {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListarTodosOf_Contrato/ListarTodos", ReplyAction="http://tempuri.org/IListarTodosOf_Contrato/ListarTodosResponse")]
        B2BSolution.Financeiro.Entidades.Contrato[] ListarTodos(B2BSolution.Financeiro.Entidades.Contrato entidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListarTodosOf_Contrato/ListarTodos", ReplyAction="http://tempuri.org/IListarTodosOf_Contrato/ListarTodosResponse")]
        System.Threading.Tasks.Task<B2BSolution.Financeiro.Entidades.Contrato[]> ListarTodosAsync(B2BSolution.Financeiro.Entidades.Contrato entidade);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IListarTodosOf_ContratoChannel : B2BSolution.Financeiro.Formulario.ContratoService.IListarTodosOf_Contrato, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListarTodosOf_ContratoClient : System.ServiceModel.ClientBase<B2BSolution.Financeiro.Formulario.ContratoService.IListarTodosOf_Contrato>, B2BSolution.Financeiro.Formulario.ContratoService.IListarTodosOf_Contrato {
        
        public ListarTodosOf_ContratoClient() {
        }
        
        public ListarTodosOf_ContratoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ListarTodosOf_ContratoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListarTodosOf_ContratoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListarTodosOf_ContratoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public B2BSolution.Financeiro.Entidades.Contrato[] ListarTodos(B2BSolution.Financeiro.Entidades.Contrato entidade) {
            return base.Channel.ListarTodos(entidade);
        }
        
        public System.Threading.Tasks.Task<B2BSolution.Financeiro.Entidades.Contrato[]> ListarTodosAsync(B2BSolution.Financeiro.Entidades.Contrato entidade) {
            return base.Channel.ListarTodosAsync(entidade);
        }
    }
}
